import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/features/Navbar";
import Footer from "@/features/Footer";
import { getInitialAuth } from "./actions/auth";
import AuthProvider from "@/features/AuthState";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const auth = await getInitialAuth();
  return (
    <AuthProvider auth={auth}>
      <html lang="en" data-theme="cupcake">
        <body className={inter.className}>
          <div className="h-screen flex flex-col justify-between p-2 md:p-4 gap-2 md:gap-4 bg-slate-200">
            <Navbar />
            <main className="flex flex-col grow overflow-y-auto p-2 scrollbar">
              {children}
            </main>
            <Footer />
          </div>
        </body>
      </html>
    </AuthProvider>
  );
}
